import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import Main from "@app/shared/layout/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          <Main>{children}</Main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
